# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "decouple" ]
  pull_request:
    branches: [ "decouple" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish KnuxTools
      run: dotnet publish KnuxTools/KnuxTools.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true -p:PublishReadyToRun=false
    - name: Publish KnuxLib
      run: dotnet publish KnuxLib/KnuxLib.csproj -c Release -r win-x64 -p:PublishSingleFile=true -p:PublishTrimmed=true -p:PublishReadyToRun=false
        
    - name: Upload KnuxTools
      uses: actions/upload-artifact@v4
      with:
        name: KnuxTools
        path: /home/runner/work/KnuxLib/KnuxLib/KnuxTools/bin/Release/net8.0/win-x64/publish
        
    - name: Upload KnuxLib
      uses: actions/upload-artifact@v4
      with:
        name: KnuxLib
        path: /home/runner/work/KnuxLib/KnuxLib/KnuxLib/bin/Release/net8.0/win-x64/publish